# @package trainer
_target_: pytorch_lightning.Trainer

# default parameters of `pytorch_lightning.Trainer`
logger: True
checkpoint_callback: False # default: True
callbacks:
default_root_dir:
gradient_clip_val: 0.0
gradient_clip_algorithm: norm
process_position: 0
num_nodes: 1
num_processes: 1
gpus: ${gpus}
auto_select_gpus: False
tpu_cores:
log_gpu_memory:
progress_bar_refresh_rate:
overfit_batches: 0.0
track_grad_norm: -1
check_val_every_n_epoch: 1
fast_dev_run: False
accumulate_grad_batches: 1
max_epochs: ${epochs}
min_epochs:
max_steps:
min_steps:
max_time:
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
limit_predict_batches: 1.0
val_check_interval: 1.0
flush_logs_every_n_steps: 100
log_every_n_steps: 50
accelerator:
sync_batchnorm: False
precision: 32
weights_summary: top
weights_save_path:
num_sanity_val_steps: 2
truncated_bptt_steps:
resume_from_checkpoint:
profiler:
benchmark: False
deterministic: False
reload_dataloaders_every_epoch: False
auto_lr_find: False
replace_sampler_ddp: True
terminate_on_nan: False
auto_scale_batch_size: False
prepare_data_per_node: True
plugins:
amp_backend: native
amp_level: O2
distributed_backend:
move_metrics_to_cpu: False
multiple_trainloader_mode: max_size_cycle
stochastic_weight_avg: False